//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoaBrugerOprettelse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrugdataEntities : DbContext
    {
        public BrugdataEntities()
            : base("name=BrugdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_initialer> T_initialer { get; set; }
        public DbSet<tbl_Manager> tbl_Manager { get; set; }
        public DbSet<tbl_360Groups> tbl_360Groups { get; set; }
    }
}
