//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leder
    {
        public Leder()
        {
            this.Blanket = new HashSet<Blanket>();
        }
    
        public int id { get; set; }
        public string initialer { get; set; }
        public string stilling { get; set; }
    
        public virtual ICollection<Blanket> Blanket { get; set; }
    }
}
