//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public int blanket_id { get; set; }
        public string status { get; set; }
        public string initialer { get; set; }
        public System.DateTime dato { get; set; }
    
        public virtual Blanket Blanket { get; set; }
    }
}
