//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoaBrugerOprettelse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medarbejder
    {
        public Medarbejder()
        {
            this.Udstyr = new HashSet<Udstyr>();
            this.Blanket = new HashSet<Blanket>();
            this.Specialprogrammer = new HashSet<Specialprogrammer>();
            this.Medarbejder_funktionspostkasse = new HashSet<Medarbejder_funktionspostkasse>();
            this.Grupper = new HashSet<Grupper>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public string initialer { get; set; }
        public string stillingsbetegnelse { get; set; }
        public Nullable<int> telefon { get; set; }
        public string afdelingsnavn { get; set; }
        public Nullable<int> område_id { get; set; }
        public string cpr { get; set; }
        public Nullable<int> fiks_id { get; set; }
        public Nullable<System.DateTime> start_dato { get; set; }
        public Nullable<System.DateTime> slut_dato { get; set; }
    
        public virtual ICollection<Udstyr> Udstyr { get; set; }
        public virtual ICollection<Blanket> Blanket { get; set; }
        public virtual ICollection<Specialprogrammer> Specialprogrammer { get; set; }
        public virtual ICollection<Medarbejder_funktionspostkasse> Medarbejder_funktionspostkasse { get; set; }
        public virtual Fiks Fiks { get; set; }
        public virtual Område Område { get; set; }
        public virtual ICollection<Grupper> Grupper { get; set; }
    }
}
