//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Område
    {
        public Område()
        {
            this.Medarbejder = new HashSet<Medarbejder>();
            this.Fiks = new HashSet<Fiks>();
            this.Grupper = new HashSet<Grupper>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
    
        public virtual ICollection<Medarbejder> Medarbejder { get; set; }
        public virtual ICollection<Fiks> Fiks { get; set; }
        public virtual ICollection<Grupper> Grupper { get; set; }
    }
}
