//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OprettelseDBEntities2 : DbContext
    {
        public OprettelseDBEntities2()
            : base("name=OprettelseDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Afdeling> Afdeling { get; set; }
        public DbSet<Fiks> Fiks { get; set; }
        public DbSet<Grupper> Grupper { get; set; }
        public DbSet<Leder> Leder { get; set; }
        public DbSet<Medarbejder> Medarbejder { get; set; }
        public DbSet<Specialprogrammer> Specialprogrammer { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Udstyr> Udstyr { get; set; }
        public DbSet<Område> Område { get; set; }
        public DbSet<Blanket> Blanket { get; set; }
        public DbSet<Medarbejder_funktionspostkasse> Medarbejder_funktionspostkasse { get; set; }
    }
}
