//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoaBrugerOprettelse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_initialer
    {
        public string PCinitialer { get; set; }
        public string Direktorat { get; set; }
        public string KDInitialer { get; set; }
        public string KDRettighed { get; set; }
        public string PensamAkasse { get; set; }
        public string AkasseRettighed { get; set; }
        public string PensamForb { get; set; }
        public string ForbRettighed { get; set; }
        public bool Fiks { get; set; }
        public string FiksRettighed { get; set; }
        public string Dialog { get; set; }
        public string Ny_loen { get; set; }
        public bool Cubus { get; set; }
        public string Specielt { get; set; }
        public bool Vikar { get; set; }
        public Nullable<System.DateTime> ForventetFratrædelse { get; set; }
        public string PcOpretAf { get; set; }
        public Nullable<System.DateTime> AendretOpdat { get; set; }
        public string AendretAf { get; set; }
        public bool Fiu { get; set; }
        public bool MR_Loen { get; set; }
        public bool MR_Pas { get; set; }
        public bool Concorde { get; set; }
        public bool FiksListe { get; set; }
        public bool SecureID_Kort { get; set; }
        public string KortNr { get; set; }
        public string PersonaleInit { get; set; }
        public int BestillingsNr { get; set; }
        public string TelefonLokal { get; set; }
        public string Stillingsbetegnelse { get; set; }
        public bool TotalSlettet { get; set; }
        public bool Acadre { get; set; }
        public bool DigitalSign { get; set; }
        public Nullable<int> UIDNr { get; set; }
        public Nullable<int> MedlemsID { get; set; }
    }
}
