//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoaBrugerOprettelse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manager
    {
        public string Manager { get; set; }
        public string E_Mail { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public int Taeller { get; set; }
        public string PersonaleAnsvarlig { get; set; }
        public string PersAnsvarligMail { get; set; }
    }
}
